"""Seed catalog: the 22 decomposition frameworks, generated by `scripts/build_catalog.py`.

Each entry: `slug`, `name`, `category`, `summary`, `when_to_use`, `source` (`"seed"`). Sessions copy
this file to `autoresearch/sessions/<slug>/catalog.json`; the reviewer appends accepted proposals there.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

CATALOG_PATH = Path(__file__).resolve().parent / "catalog.json"


def load_seed_catalog() -> list[dict[str, Any]]:
    """A fresh list of the committed seed entries (callers may mutate their copy)."""
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
